name: Test

on:
  pull_request:
  push:

jobs:
  type_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Dep
        run: pnpm install
      - name: Test
        run: pnpm test
  Dry_Publish:
    runs-on: ubuntu-latest
    name: Dry Publish
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dep
        run: pnpm install
      - name: Dry publish
        run: pnpm publish --dry-run --no-git-checks
      
